### ISSUE TITLE
Crash upon going to layer

### ISSUE THREAD

**Issue by jacob-blagg** [altalk23/EditorCollab#14]
### Platform

Windows - Standalone

### Editor Collab Version

beta 0.5.0

### Mods Installed

Betteredit 4.0.5 betterinfo crash-logger draw-divide every-key-jumps FadeMusicOnDeath GDliveeditor GDshare Labeldeath song-search textureldr uirecolor

### Cross-Mod Interaction

No

### Steps to Reproduce

1) Join the multiplayer server
2) Select an object
3) Press the "Go To Layer" button or change layers
4) crash

### Crash Report

[crash-log.log](https://github.com/altalk23/EditorCollab/files/9641691/crash-log.log)

### Additional Information

women

**Comment by jacob-blagg** [comment]
Just realised that changing layers at all crash the game

**Comment by altalk23** [comment]
Good job on the first bug that I dont even know how it can happen!
The stack trace seems to only have betteredit and cocos stuff so idk what is going on at first, I'll try to have a look at it

**Comment by altalk23** [comment]
Nvm im dumb
