### ISSUE TITLE
Mod doesn't work

### ISSUE THREAD

**Issue by MegaSa1nt** [altalk23/EditorCollab#24]
### Platform

Windows - Standalone

### Editor Collab Version

v0.5.3

### Mods Installed

BetterEdit v4.0.5

### Cross-Mod Interaction

No

### Expected Behavior

Something changes in levels

### Actual Behavior

Nothing happened

### Steps to Reproduce

1) I injected dll with GDHM
2) Restarted game
3) Nothing

### Additional Information

I'm doing this on GDPS

**Comment by altalk23** [comment]
Did you create an account from the options screen
