### ISSUE TITLE
Share button

### ISSUE THREAD

**Issue by NNonick1** [altalk23/EditorCollab#26]
### Your Question

I didn't find a button to become a level host.  Where is this button located?

**Comment by altalk23** [comment]
What is your username?

**Comment by NNonick1** [comment]
in editor collab NNonick
In GD NNonick

**Comment by altalk23** [comment]
You need to go to the [patreon](https://www.patreon.com/alk1m123) and get a host subscription to get hosting permissions

**Comment by NNonick1** [comment]
> You need to go to the [patreon](https://www.patreon.com/alk1m123) and get a host subscription to get hosting permissions

Ok, thanks
