### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kucer0043** [altalk23/EditorCollab#31]
### Platform

Windows - Geode

### Editor Collab Version

v1.5.1

### Cross-Mod Interaction

Yes

### Expected Behavior

-

### Actual Behavior

Image: 
<img width="329" alt="Error" src="https://user-images.githubusercontent.com/61726070/214623091-f354dd62-71df-42c4-91e3-b18088a93f5b.png">

### Steps to Reproduce

Pls dowload my Geometry Dash
My Geometry Dash: https://drive.google.com/file/d/1FSLl19uEgbDMhyewpuWvyO9AwpGxnFdz/view?usp=share_link

### Additional Information

logs folder is empty

**Comment by altalk23** [comment]
EditorCollab doesn't have a 1.0.0 nightly version. What EditorCollab and Geode version are you using?

**Comment by kucer0043** [comment]
Sorry I got it mixed up
Geoge - 1.0.0 Nightly
EditorCollab - 1.5.1

**Comment by altalk23** [comment]
Alright, EditorCollab has not yet been updated for 1.0.0-beta version, will compile that when I have time

**Comment by altalk23** [comment]
Fixed in latest update
