### ISSUE TITLE
How do you share your level

### ISSUE THREAD

**Issue by Ludll** [altalk23/EditorCollab#44]
### Your Question

How do I share my level?

**Comment by altalk23** [comment]
First, you subscribe to the patreon so I can give you host permissions. Then a share button at the top right opens up when you are editing a level. You can then use the menu to share and edit your level.
![スクリーンショット 2023-10-16 17 50 16](https://github.com/altalk23/EditorCollab/assets/45172705/23f5b114-20be-4c36-98a1-01dc98da34ba)
